# Generated by Django 4.2.26 on 2026-01-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_events_alter_eventquery_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='image',
        ),
        migrations.AddField(
            model_name='events',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
