# Generated by Django 4.2.26 on 2026-01-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_events_image_events_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='gallery')),
            ],
        ),
    ]
